# -*- coding: utf-8 -*-
"""
Django settings for qapy project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

import json

from django.contrib.messages import constants as message_constants
from django.core.exceptions import ImproperlyConfigured

from unipath import Path


BASE_DIR = Path(__file__).ancestor(3)
TMP_DIR = Path('/tmp')


with open(BASE_DIR.child("secrets.json")) as f:
    secrets = json.loads(f.read())


def get_secret(setting, secrets=secrets):
    """Get secret setting or fail with ImproperlyConfigured."""
    try:
        return secrets[setting]
    except KeyError:
        raise ImproperlyConfigured(
            "Set the {} environment variable.".format(setting))


MEDIA_ROOT = BASE_DIR.child('media')
STATIC_ROOT = BASE_DIR.child('static')
STATICFILES_DIRS = []

SITE_ID = 1

DEBUG = False

ALLOWED_HOSTS = []

SECRET_KEY = get_secret('SECRET_KEY')

WSGI_APPLICATION = 'qapy.wsgi.application'

ROOT_URLCONF = 'qapy.urls'

STATIC_URL = '/__static__/'
STATIC_URL = '/__media__/'

X_FRAME_OPTIONS = 'DENY'

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_L10N = True
USE_TZ = True

ADMINS = [
    ("Antoine Pinsard", "antoine.pinsard@gmail.com"),
]
MANAGERS = [
    ("Antoine Pinsard", "antoine.pinsard@gmail.com"),
]


INSTALLED_APPS = [
    'ui',

    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'bank',
]


MIDDLEWARE_CLASSES = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'qapy',
        'USER': get_secret('DB_USER'),
        'PASSWORD': get_secret('DB_PASSWD'),
        'TEST': {
            'CHARSET': 'utf-8',
        },
    },
}

MESSAGE_TAGS = {
    message_constants.DEBUG: 'info',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',
}
